#coding=utf-8
"""
Django settings for MyDjango project.

Generated by 'django-admin startproject' using Django 2.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
#-----------------------------------------------------------------
#项目路径
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/


#--------------------------------------------------------------------
#密码配置
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '--)&(hofup)y%v8j72xd$mv9$03uu08z#9dq%*(1huw%^rbmpw'


#-------------------------------------------------------------------
#调式模式
#发布时将DEBUG=False
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


#-------------------------------------------------------------------
#域名访问权限
ALLOWED_HOSTS = ["127.0.0.1"]



#------------------------------------------------------------------
# Application definition
#App列表
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #添加项目应用index
    'index',
    #添加user app
    'user'
]

#-----------------------------------------------------------------
#中间件的配置
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MyDjango.urls'

#----------------------------------------------------
#模板配置
TEMPLATES = [
    {
        #定义模板引擎，用于识别模板里的变量和指令
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        #模板所在的路径
        'DIRS': [os.path.join(BASE_DIR,'templates')],

        #是否在app查看模板文件
        'APP_DIRS': True,

        #用于填充模板引擎里的变量或指令。一般不修改
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MyDjango.wsgi.application'

#--------------------------------------------------------
# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases


#数据库的配置
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/


#资源路由    配置静态文件(css/javaScript)的存放static的名称不能改,只能在app目录下
STATIC_URL = '/static/'


#资源集合STATICFILES_DIRS是设置静态文件在别的文件下存放而部总是放在app/static下
#os.path.join(BASE_DIR,'static') 这个是用来设置文件路径的BASE_DIR为绝对路径，后面的参数为文件在项目中的位置
STATICFILES_DIRS=[os.path.join(BASE_DIR,'static'),os.path.join(BASE_DIR,'index/Mystatic')]

#STATIC_ROOT=os.path.join(BASE_DIR,"AllsStatic")


#媒体资源MEDIA 用来设置用户头像 歌曲等

#媒体文件路径
MEDIA_URL="/media/"

#获取media的完整路径信息
MEDIA_ROOT=os.path.join(BASE_DIR,"media")
